name: Python Lint and Test (L+T)
run-name_L+T triggered by ${{ github.actor }}


on: 
  push: 
      - main

  pull_request:
      branches:
        - main

jobs:
  lint:
    runs-on: ubunt-latest
    steps:
      - name: Checkout out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # fetch all history for all tags and branches

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install -e .
          python -m pip install -e .[lint]
      
      - name: Lint code
        run: ruff check --output-format=github .
          
